base_config: configs/kitti/kitti.yaml

exp_name: kitti/sqeuence00



data_specs:
  data_path: '/disk2/wh/code/nerfloam-modify/data/kitti_example/sequences/00'
  use_gt: False
  max_depth: 40
  min_depth: 5

tracker_specs:
  start_frame: 0
  end_frame: -1
  read_offset: 1