base_config: configs/maicity/maicity.yaml

exp_name: maicity/sqeuence00


data_specs:
  data_path: '/home/pl21n4/dataset/mai_city/bin/sequences/00'
  use_gt: False
  max_depth: 50.0
  min_depth: 1.5

tracker_specs:
  start_frame: 0
  end_frame: 699
  read_offset: 1