log_dir: './logs'
decoder: lidar
dataset: maicity

criteria:
  sdf_weight: 10000.0
  fs_weight: 1
  eiko_weight: 0.1
  sdf_truncation: 0.30

decoder_specs:
  depth: 2
  width: 128
  in_dim: 8
  skips: []
  embedder: ffe
  multires: 0
  # if use mult layer, set level > 1
  # if level == 1, only position encoding
  level: 3

tracker_specs:
  N_rays: 2048
  learning_rate: 0.005
  step_size: 0.2
  max_voxel_hit: 20
  num_iterations: 20

mapper_specs:
  N_rays_each: 2048
  use_local_coord: False
  voxel_size: 0.2
  step_size: 0.5
  window_size: 4
  num_iterations: 20
  max_voxel_hit: 20
  final_iter: True
  mesh_res: 2
  learning_rate_emb: 0.03
  learning_rate_decorder: 0.005
  learning_rate_pose: 0.001
  freeze_frame: 5
  keyframe_gap: 8
  remove_back: False
  key_distance: 12

debug_args:
  verbose: False
  mesh_freq: 100
